version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - motchang
  assignees:
  - motchang
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
  - dependency-name: rubocop
    versions:
    - 1.9.0
    - 1.9.1
  - dependency-name: puma
    versions:
    - 5.2.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: pry-stack_explorer
    versions:
    - 0.6.0
