# -*- mode: dockerfile -*-
FROM ruby:3.0.2

ENV ENTRYKIT_VERSION 0.4.0
ENV EDITOR vim

WORKDIR /webapp

RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime                                                                                    \
  && dpkg-reconfigure --frontend noninteractive tzdata                                                                                  \
  && wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz     \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz                                                                            \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz                                                                                   \
  && mv entrykit /bin/entrykit                                                                                                          \
  && chmod +x /bin/entrykit                                                                                                             \
  && entrykit --symlink                                                                                                                 \
  && curl -sL https://deb.nodesource.com/setup_10.x | bash -                                                                             \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -                                                                  \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list                                      \
  && sh -c 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'                                         \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'   \
  && apt-get update && apt-get install -y                                                                                               \
    nodejs                                                                                                                              \
    yarn                                                                                                                                \
    zip                                                                                                                                 \
    vim                                                                                                                                 \
    mupdf-tools                                                                                                                         \
    google-chrome-stable                                                                                                                \
  && gem install foreman bundler                                                                                                        \
  && CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`                                                \
  && wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/                           \
  && unzip ~/chromedriver_linux64.zip -d ~/                                                                                             \
  && rm ~/chromedriver_linux64.zip                                                                                                      \
  && chown root:root ~/chromedriver                                                                                                     \
  && chmod 755 ~/chromedriver                                                                                                           \
  && mv ~/chromedriver /usr/bin/chromedriver                                                                                            \
  && apt-get clean

ENTRYPOINT [ \
  "prehook", "rm -f tmp/pids/*", "--", \
  "prehook", "ruby -v", "--", \
  "prehook", "node -v", "--" \
]
