name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ahmadnassri/action-dependabot-auto-merge@v2.4.0
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          config: .github/dependabot-auto-merge.yml
