name: auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.4.0
        with:
          target: minor
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
